theme: minima
title: MSc Artificial Intelligence
author: Nithya Kanakavelu
email: nithya8483@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This displays my activities and assignments performed towards my learning

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
